pipeline {
	agent {
		label 'docker-agent'
	}
	
	environment{
		BUILD_IMAGES = 'najimattat/e-commers'
	}
	
	stages{
		stage("Checkout"){
			steps{
				echo 'checking out SCM'
				checkout scm
			}
		}
		stage("build"){
			steps{
				dir('docker/my-ecommerce'){
					echo 'Build docker image'
					sh 'docker build -t ${BUILD_IMAGE}:${BUILD_NUMBER} .'
				}
			}
		}
		stage("push"){
			steps{
				echo 'docker image push to dockerHub'
				sh ```
					'docker push ${BIULD_IMAGE}:${BUILD_NUMBER}'

				     ```
			}
		}

		stage("Image"){
			steps{
				echo 'docker image'
				sh 'docker images'
			}
		}
		stage("stop"){
			steps{
				echo 'delete container'
				sh 'docker stop app || true'
				sh 'docker rm app || true'
			}
		}

		stage("Run"){
			steps{
				echo 'running container using docker image'
				sh 'docker run -d --name app -p 8090:80 e-commers:${BUILD_NUMBER}'
			}
		}
		stage("check containers"){
			steps{
				echo 'docker containers '
				sh 'docker ps'
			}
		}	
			
	}
	post { 
		success { 
			echo 'E-commerce application deployed successfully!' 
		} 
		failure { 
			echo 'Build or deployment failed.' 
		} 
	}
}