pipeline {
	agent {
		label 'docker-agent'
	}
	
	environment{
		IMAGE_NAME = 'najimattar/e-commers'
		IMAGE_TAG = '${BUILD_NUMBER}'
	}
	
	stages{
		stage("Checkout"){
			steps{
				echo 'checking out SCM'
				checkout scm
			}
		}
		stage("build"){
			steps{
				dir('docker/my-ecommerce'){
					echo 'Build docker image'
					sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
				}
			}
		}
		stage("Image scan"){
			steps{
				echo 'docker image scan...'
				sh '''
					trivy --version
					trivy image ${IMAGE_NAME}:${IMAGE_TAG}

				     '''
			}
		}
		stage("push"){
			steps{
				echo 'docker image push to dockerHub'
				sh '''
					docker push ${IMAGE_NAME}:${IMAGE_TAG}

				     '''
			}
		}

		stage("Image"){
			steps{
				echo 'docker images..'
				sh 'docker images'
			}
		}
		stage("stop"){
			steps{
				echo 'delete container...'
				sh '''
					docker stop app || true
					docker rm app || true
				'''
			}
		}

		stage("Run"){
			steps{
				echo 'running container using docker image'
				sh 'docker run -d --name app -p 8090:80 ${IMAGE_NAME}:${IMAGE_TAG}'
			}
		}
		stage("check containers"){
			steps{
				echo 'docker containers '
				sh 'docker ps'
			}
		}	
			
	}
	post { 
		success { 
			echo 'E-commerce application deployed successfully!' 
		} 
		failure { 
			echo 'Build or deployment failed.' 
		} 
	}
}
